# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI-Layouts/qAndora.ui'
#
# Created: Sat Feb  7 20:50:37 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 372)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setHorizontalSpacing(0)
        self.gridLayout_9.setVerticalSpacing(4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setHorizontalSpacing(0)
        self.gridLayout_8.setVerticalSpacing(4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stationBox = QtGui.QComboBox(self.centralwidget)
        self.stationBox.setMinimumSize(QtCore.QSize(0, 32))
        self.stationBox.setMaximumSize(QtCore.QSize(16777215, 32))
        self.stationBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.stationBox.setBaseSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stationBox.setFont(font)
        self.stationBox.setObjectName("stationBox")
        self.gridLayout_4.addWidget(self.stationBox, 0, 3, 1, 1)
        self.settingsButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsButton.sizePolicy().hasHeightForWidth())
        self.settingsButton.setSizePolicy(sizePolicy)
        self.settingsButton.setMinimumSize(QtCore.QSize(32, 32))
        self.settingsButton.setMaximumSize(QtCore.QSize(32, 32))
        self.settingsButton.setText("")
        self.settingsButton.setIconSize(QtCore.QSize(22, 22))
        self.settingsButton.setObjectName("settingsButton")
        self.gridLayout_4.addWidget(self.settingsButton, 0, 4, 1, 1)
        self.skipButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skipButton.sizePolicy().hasHeightForWidth())
        self.skipButton.setSizePolicy(sizePolicy)
        self.skipButton.setMinimumSize(QtCore.QSize(32, 32))
        self.skipButton.setMaximumSize(QtCore.QSize(32, 32))
        self.skipButton.setText("")
        self.skipButton.setIconSize(QtCore.QSize(22, 22))
        self.skipButton.setObjectName("skipButton")
        self.gridLayout_4.addWidget(self.skipButton, 0, 1, 1, 1)
        self.playPauseButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playPauseButton.sizePolicy().hasHeightForWidth())
        self.playPauseButton.setSizePolicy(sizePolicy)
        self.playPauseButton.setMinimumSize(QtCore.QSize(32, 32))
        self.playPauseButton.setMaximumSize(QtCore.QSize(32, 32))
        self.playPauseButton.setText("")
        self.playPauseButton.setIconSize(QtCore.QSize(22, 22))
        self.playPauseButton.setObjectName("playPauseButton")
        self.gridLayout_4.addWidget(self.playPauseButton, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setHorizontalSpacing(4)
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.albumImage = QtGui.QLabel(self.centralwidget)
        self.albumImage.setMinimumSize(QtCore.QSize(128, 128))
        self.albumImage.setMaximumSize(QtCore.QSize(128, 128))
        self.albumImage.setFrameShape(QtGui.QFrame.StyledPanel)
        self.albumImage.setFrameShadow(QtGui.QFrame.Sunken)
        self.albumImage.setScaledContents(True)
        self.albumImage.setAlignment(QtCore.Qt.AlignCenter)
        self.albumImage.setIndent(0)
        self.albumImage.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.albumImage.setObjectName("albumImage")
        self.gridLayout_7.addWidget(self.albumImage, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(4, 4, 0, -1)
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.titleLabel = QtGui.QLabel(self.centralwidget)
        self.titleLabel.setText("")
        self.titleLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setIndent(0)
        self.titleLabel.setOpenExternalLinks(True)
        self.titleLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout_3.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.artistLabel = QtGui.QLabel(self.centralwidget)
        self.artistLabel.setText("")
        self.artistLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.artistLabel.setWordWrap(True)
        self.artistLabel.setIndent(0)
        self.artistLabel.setOpenExternalLinks(True)
        self.artistLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.artistLabel.setObjectName("artistLabel")
        self.gridLayout_3.addWidget(self.artistLabel, 1, 0, 1, 1)
        self.albumLabel = QtGui.QLabel(self.centralwidget)
        self.albumLabel.setText("")
        self.albumLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.albumLabel.setWordWrap(True)
        self.albumLabel.setIndent(0)
        self.albumLabel.setOpenExternalLinks(True)
        self.albumLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.albumLabel.setObjectName("albumLabel")
        self.gridLayout_3.addWidget(self.albumLabel, 2, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setContentsMargins(-1, -1, 4, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.positionLabel = QtGui.QLabel(self.centralwidget)
        self.positionLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.positionLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.positionLabel.setText("")
        self.positionLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.positionLabel.setIndent(0)
        self.positionLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.positionLabel.setObjectName("positionLabel")
        self.gridLayout_2.addWidget(self.positionLabel, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setHorizontalSpacing(4)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.infoButton = QtGui.QPushButton(self.centralwidget)
        self.infoButton.setMinimumSize(QtCore.QSize(32, 32))
        self.infoButton.setMaximumSize(QtCore.QSize(32, 32))
        self.infoButton.setIconSize(QtCore.QSize(22, 22))
        self.infoButton.setObjectName("infoButton")
        self.gridLayout.addWidget(self.infoButton, 0, 0, 1, 1)
        self.loveButton = QtGui.QPushButton(self.centralwidget)
        self.loveButton.setMinimumSize(QtCore.QSize(32, 32))
        self.loveButton.setMaximumSize(QtCore.QSize(32, 32))
        self.loveButton.setText("")
        self.loveButton.setIconSize(QtCore.QSize(22, 22))
        self.loveButton.setObjectName("loveButton")
        self.gridLayout.addWidget(self.loveButton, 0, 1, 1, 1)
        self.tiredButton = QtGui.QPushButton(self.centralwidget)
        self.tiredButton.setMinimumSize(QtCore.QSize(32, 32))
        self.tiredButton.setMaximumSize(QtCore.QSize(32, 32))
        self.tiredButton.setText("")
        self.tiredButton.setIconSize(QtCore.QSize(22, 22))
        self.tiredButton.setObjectName("tiredButton")
        self.gridLayout.addWidget(self.tiredButton, 0, 2, 1, 1)
        self.banButton = QtGui.QPushButton(self.centralwidget)
        self.banButton.setMinimumSize(QtCore.QSize(32, 32))
        self.banButton.setMaximumSize(QtCore.QSize(32, 32))
        self.banButton.setText("")
        self.banButton.setIconSize(QtCore.QSize(22, 22))
        self.banButton.setObjectName("banButton")
        self.gridLayout.addWidget(self.banButton, 0, 3, 1, 1)
        self.muteButton = QtGui.QPushButton(self.centralwidget)
        self.muteButton.setMinimumSize(QtCore.QSize(32, 32))
        self.muteButton.setMaximumSize(QtCore.QSize(32, 32))
        self.muteButton.setText("")
        self.muteButton.setIconSize(QtCore.QSize(22, 22))
        self.muteButton.setObjectName("muteButton")
        self.gridLayout.addWidget(self.muteButton, 0, 4, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.volumeSlider = QtGui.QSlider(self.centralwidget)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.gridLayout_6.addWidget(self.volumeSlider, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.historyList = QtGui.QListWidget(self.centralwidget)
        self.historyList.setMinimumSize(QtCore.QSize(0, 0))
        self.historyList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.historyList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.historyList.setAutoScrollMargin(64)
        self.historyList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.historyList.setProperty("showDropIndicator", False)
        self.historyList.setAlternatingRowColors(True)
        self.historyList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.historyList.setIconSize(QtCore.QSize(64, 64))
        self.historyList.setGridSize(QtCore.QSize(64, 64))
        self.historyList.setObjectName("historyList")
        self.gridLayout_9.addWidget(self.historyList, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "qAndora", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.skipButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Skip Song", None, QtGui.QApplication.UnicodeUTF8))
        self.playPauseButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Pause Song", None, QtGui.QApplication.UnicodeUTF8))
        self.infoButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Song Info", None, QtGui.QApplication.UnicodeUTF8))
        self.loveButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Love this Song", None, QtGui.QApplication.UnicodeUTF8))
        self.tiredButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Tired of this Song", None, QtGui.QApplication.UnicodeUTF8))
        self.banButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Ban this Song", None, QtGui.QApplication.UnicodeUTF8))

