# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI-Layouts/qPreferences.ui'
#
# Created: Wed Dec 17 03:01:58 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_qPreferences(object):
    def setupUi(self, qPreferences):
        qPreferences.setObjectName("qPreferences")
        qPreferences.resize(409, 265)
        self.horizontalLayout = QtGui.QHBoxLayout(qPreferences)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prefWidget = QtGui.QTabWidget(qPreferences)
        self.prefWidget.setEnabled(True)
        self.prefWidget.setObjectName("prefWidget")
        self.aboutTab = QtGui.QWidget()
        self.aboutTab.setObjectName("aboutTab")
        self.verticalLayout = QtGui.QVBoxLayout(self.aboutTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.aboutLabel = QtGui.QLabel(self.aboutTab)
        self.aboutLabel.setWordWrap(True)
        self.aboutLabel.setOpenExternalLinks(True)
        self.aboutLabel.setObjectName("aboutLabel")
        self.verticalLayout.addWidget(self.aboutLabel)
        self.prefWidget.addTab(self.aboutTab, "")
        self.generlTab = QtGui.QWidget()
        self.generlTab.setAccessibleName("")
        self.generlTab.setObjectName("generlTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.generlTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.userFrame = QtGui.QFrame(self.generlTab)
        self.userFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.userFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.userFrame.setObjectName("userFrame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.userFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.userLabel = QtGui.QLabel(self.userFrame)
        self.userLabel.setObjectName("userLabel")
        self.horizontalLayout_2.addWidget(self.userLabel)
        self.logoutButton = QtGui.QToolButton(self.userFrame)
        self.logoutButton.setObjectName("logoutButton")
        self.horizontalLayout_2.addWidget(self.logoutButton)
        self.verticalLayout_2.addWidget(self.userFrame)
        self.qualityFrame = QtGui.QFrame(self.generlTab)
        self.qualityFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.qualityFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.qualityFrame.setObjectName("qualityFrame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.qualityFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.qualityLabel = QtGui.QLabel(self.qualityFrame)
        self.qualityLabel.setObjectName("qualityLabel")
        self.horizontalLayout_3.addWidget(self.qualityLabel)
        self.qualityBox = QtGui.QComboBox(self.qualityFrame)
        self.qualityBox.setObjectName("qualityBox")
        self.horizontalLayout_3.addWidget(self.qualityBox)
        self.verticalLayout_2.addWidget(self.qualityFrame)
        self.notificationFrame = QtGui.QFrame(self.generlTab)
        self.notificationFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.notificationFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.notificationFrame.setObjectName("notificationFrame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.notificationFrame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.notificationLabel = QtGui.QLabel(self.notificationFrame)
        self.notificationLabel.setObjectName("notificationLabel")
        self.horizontalLayout_4.addWidget(self.notificationLabel)
        self.notificationBox = QtGui.QComboBox(self.notificationFrame)
        self.notificationBox.setObjectName("notificationBox")
        self.horizontalLayout_4.addWidget(self.notificationBox)
        self.verticalLayout_2.addWidget(self.notificationFrame)
        self.prefWidget.addTab(self.generlTab, "")
        self.filterTab = QtGui.QWidget()
        self.filterTab.setObjectName("filterTab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.filterTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtGui.QFrame(self.filterTab)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.liveCheck = QtGui.QCheckBox(self.frame)
        self.liveCheck.setChecked(False)
        self.liveCheck.setObjectName("liveCheck")
        self.horizontalLayout_5.addWidget(self.liveCheck)
        self.editCheck = QtGui.QCheckBox(self.frame)
        self.editCheck.setObjectName("editCheck")
        self.horizontalLayout_5.addWidget(self.editCheck)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.filterTab)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.remixCheck = QtGui.QCheckBox(self.frame_2)
        self.remixCheck.setObjectName("remixCheck")
        self.horizontalLayout_6.addWidget(self.remixCheck)
        self.rateCheck = QtGui.QCheckBox(self.frame_2)
        self.rateCheck.setObjectName("rateCheck")
        self.horizontalLayout_6.addWidget(self.rateCheck)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.label = QtGui.QLabel(self.filterTab)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.prefWidget.addTab(self.filterTab, "")
        self.horizontalLayout.addWidget(self.prefWidget)

        self.retranslateUi(qPreferences)
        self.prefWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(qPreferences)

    def retranslateUi(self, qPreferences):
        qPreferences.setWindowTitle(QtGui.QApplication.translate("qPreferences", "qAndora - Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutLabel.setText(QtGui.QApplication.translate("qPreferences", "<html><head/><body><p>qAndora is a cross platform, open source, <a href=\"www.pandora.com\"><span style=\" text-decoration: underline; color:#0057ae;\">Pandora Internet Radio</span></a> client written in <a href=\"https://www.python.org/\"><span style=\" text-decoration: underline; color:#0057ae;\">Python</span></a> using <a href=\"http://qt-project.org/\"><span style=\" text-decoration: underline; color:#0057ae;\">Qt</span></a> by <a href=\"http://www.jeffhoogland.com/\"><span style=\" text-decoration: underline; color:#0057ae;\">Jeff Hoogland</span></a>.<br/><br/><a href=\"https://github.com/JeffHoogland/qAndora\"><span style=\" text-decoration: underline; color:#0057ae;\">qAndora source on GitHub</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.prefWidget.setTabText(self.prefWidget.indexOf(self.aboutTab), QtGui.QApplication.translate("qPreferences", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.userLabel.setText(QtGui.QApplication.translate("qPreferences", "<b>Change User:", None, QtGui.QApplication.UnicodeUTF8))
        self.logoutButton.setText(QtGui.QApplication.translate("qPreferences", "Logout", None, QtGui.QApplication.UnicodeUTF8))
        self.qualityLabel.setText(QtGui.QApplication.translate("qPreferences", "<b>Audio Quality:", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationLabel.setText(QtGui.QApplication.translate("qPreferences", "<b>Desktop Notifications:", None, QtGui.QApplication.UnicodeUTF8))
        self.prefWidget.setTabText(self.prefWidget.indexOf(self.generlTab), QtGui.QApplication.translate("qPreferences", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.liveCheck.setText(QtGui.QApplication.translate("qPreferences", "Filter live songs", None, QtGui.QApplication.UnicodeUTF8))
        self.editCheck.setText(QtGui.QApplication.translate("qPreferences", "Filter edit songs", None, QtGui.QApplication.UnicodeUTF8))
        self.remixCheck.setText(QtGui.QApplication.translate("qPreferences", "Filter remix songs", None, QtGui.QApplication.UnicodeUTF8))
        self.rateCheck.setText(QtGui.QApplication.translate("qPreferences", "Ban Filtered Songs", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("qPreferences", "<html><head/><body><p>Remix are songs that have &quot;mix&quot; in () or []</p><p>Live are songs that have &quot;live&quot; in () or []</p><p>Edit are songs that contain &quot;edit&quot; in () or []</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.prefWidget.setTabText(self.prefWidget.indexOf(self.filterTab), QtGui.QApplication.translate("qPreferences", "Filters", None, QtGui.QApplication.UnicodeUTF8))

