# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI-Layouts/qPreferences.ui'
#
# Created: Sat Feb  7 19:49:38 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_qPreferences(object):
    def setupUi(self, qPreferences):
        qPreferences.setObjectName("qPreferences")
        qPreferences.resize(369, 317)
        qPreferences.setMinimumSize(QtCore.QSize(369, 317))
        qPreferences.setMaximumSize(QtCore.QSize(369, 317))
        self.gridLayout_13 = QtGui.QGridLayout(qPreferences)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tabWidget = QtGui.QTabWidget(qPreferences)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setHorizontalSpacing(0)
        self.gridLayout_14.setVerticalSpacing(4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.nameLabel = QtGui.QLabel(self.tab_4)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_14.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.nameEdit = QtGui.QLineEdit(self.tab_4)
        self.nameEdit.setMinimumSize(QtCore.QSize(0, 32))
        self.nameEdit.setMaximumSize(QtCore.QSize(16777215, 32))
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_14.addWidget(self.nameEdit, 1, 0, 1, 1)
        self.passwordLabel = QtGui.QLabel(self.tab_4)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout_14.addWidget(self.passwordLabel, 2, 0, 1, 1)
        self.passwordEdit = QtGui.QLineEdit(self.tab_4)
        self.passwordEdit.setMinimumSize(QtCore.QSize(0, 32))
        self.passwordEdit.setMaximumSize(QtCore.QSize(16777215, 32))
        self.passwordEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.gridLayout_14.addWidget(self.passwordEdit, 3, 0, 1, 1)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setHorizontalSpacing(4)
        self.gridLayout_15.setVerticalSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.loginButton = QtGui.QPushButton(self.tab_4)
        self.loginButton.setMinimumSize(QtCore.QSize(0, 32))
        self.loginButton.setObjectName("loginButton")
        self.gridLayout_15.addWidget(self.loginButton, 0, 0, 1, 1)
        self.accountButton = QtGui.QPushButton(self.tab_4)
        self.accountButton.setMinimumSize(QtCore.QSize(0, 32))
        self.accountButton.setObjectName("accountButton")
        self.gridLayout_15.addWidget(self.accountButton, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_15, 4, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(4, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.userLabel = QtGui.QLabel(self.tab_4)
        self.userLabel.setObjectName("userLabel")
        self.gridLayout.addWidget(self.userLabel, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.logoutButton = QtGui.QToolButton(self.tab_4)
        self.logoutButton.setMinimumSize(QtCore.QSize(86, 32))
        self.logoutButton.setMaximumSize(QtCore.QSize(86, 32))
        self.logoutButton.setObjectName("logoutButton")
        self.gridLayout.addWidget(self.logoutButton, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setContentsMargins(4, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.qualityLabel = QtGui.QLabel(self.tab_4)
        self.qualityLabel.setObjectName("qualityLabel")
        self.gridLayout_2.addWidget(self.qualityLabel, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.qualityBox = QtGui.QComboBox(self.tab_4)
        self.qualityBox.setMinimumSize(QtCore.QSize(86, 32))
        self.qualityBox.setMaximumSize(QtCore.QSize(86, 32))
        self.qualityBox.setObjectName("qualityBox")
        self.gridLayout_2.addWidget(self.qualityBox, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setContentsMargins(4, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.notificationLabel = QtGui.QLabel(self.tab_4)
        self.notificationLabel.setObjectName("notificationLabel")
        self.gridLayout_3.addWidget(self.notificationLabel, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        self.notificationBox = QtGui.QComboBox(self.tab_4)
        self.notificationBox.setMinimumSize(QtCore.QSize(86, 32))
        self.notificationBox.setMaximumSize(QtCore.QSize(86, 32))
        self.notificationBox.setObjectName("notificationBox")
        self.gridLayout_3.addWidget(self.notificationBox, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.liveCheck = QtGui.QCheckBox(self.tab_2)
        self.liveCheck.setChecked(False)
        self.liveCheck.setObjectName("liveCheck")
        self.gridLayout_7.addWidget(self.liveCheck, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 1, 1, 2)
        self.rateCheck = QtGui.QCheckBox(self.tab_2)
        self.rateCheck.setObjectName("rateCheck")
        self.gridLayout_7.addWidget(self.rateCheck, 1, 0, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 1, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.editCheck = QtGui.QCheckBox(self.tab_2)
        self.editCheck.setObjectName("editCheck")
        self.gridLayout_8.addWidget(self.editCheck, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 0, 1, 1, 2)
        self.remixCheck = QtGui.QCheckBox(self.tab_2)
        self.remixCheck.setObjectName("remixCheck")
        self.gridLayout_8.addWidget(self.remixCheck, 1, 0, 1, 2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem6, 1, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setContentsMargins(4, -1, -1, -1)
        self.gridLayout_10.setHorizontalSpacing(0)
        self.gridLayout_10.setVerticalSpacing(4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_10.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_17 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.aboutLabel = QtGui.QLabel(self.tab_3)
        self.aboutLabel.setWordWrap(True)
        self.aboutLabel.setOpenExternalLinks(True)
        self.aboutLabel.setObjectName("aboutLabel")
        self.gridLayout_6.addWidget(self.aboutLabel, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_13.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(qPreferences)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(qPreferences)

    def retranslateUi(self, qPreferences):
        qPreferences.setWindowTitle(QtGui.QApplication.translate("qPreferences", "qAndora - Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setText(QtGui.QApplication.translate("qPreferences", "Pandora Login:", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordLabel.setText(QtGui.QApplication.translate("qPreferences", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.loginButton.setText(QtGui.QApplication.translate("qPreferences", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.accountButton.setText(QtGui.QApplication.translate("qPreferences", "Create Account", None, QtGui.QApplication.UnicodeUTF8))
        self.userLabel.setText(QtGui.QApplication.translate("qPreferences", "Change User:", None, QtGui.QApplication.UnicodeUTF8))
        self.logoutButton.setText(QtGui.QApplication.translate("qPreferences", "Logout", None, QtGui.QApplication.UnicodeUTF8))
        self.qualityLabel.setText(QtGui.QApplication.translate("qPreferences", "Audio Quality:", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationLabel.setText(QtGui.QApplication.translate("qPreferences", "Desktop Notifications:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("qPreferences", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.liveCheck.setText(QtGui.QApplication.translate("qPreferences", "Filter live songs", None, QtGui.QApplication.UnicodeUTF8))
        self.rateCheck.setText(QtGui.QApplication.translate("qPreferences", "Ban Filtered Songs", None, QtGui.QApplication.UnicodeUTF8))
        self.editCheck.setText(QtGui.QApplication.translate("qPreferences", "Filter edit songs", None, QtGui.QApplication.UnicodeUTF8))
        self.remixCheck.setText(QtGui.QApplication.translate("qPreferences", "Filter remix songs", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("qPreferences", "<html><head/><body><p>Remix are songs that have &quot;mix&quot; in () or []</p><p>Live are songs that have &quot;live&quot; in () or []</p><p>Edit are songs that contain &quot;edit&quot; in () or []</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("qPreferences", "<b>Please note:</b> <br>Filtered songs may count against your skip limit.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("qPreferences", "Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutLabel.setText(QtGui.QApplication.translate("qPreferences", "<html><head/><body><p>qAndora is a cross platform, open source, <a href=\"www.pandora.com\"><span style=\" text-decoration: underline; color:#0057ae;\">Pandora Internet Radio</span></a> client written in <a href=\"https://www.python.org/\"><span style=\" text-decoration: underline; color:#0057ae;\">Python</span></a> using <a href=\"http://qt-project.org/\"><span style=\" text-decoration: underline; color:#0057ae;\">Qt</span></a> by <a href=\"http://www.jeffhoogland.com/\"><span style=\" text-decoration: underline; color:#0057ae;\">Jeff Hoogland</span></a>.<br/><br/><a href=\"https://github.com/JeffHoogland/qAndora\"><span style=\" text-decoration: underline; color:#0057ae;\">qAndora source on GitHub</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("qPreferences", "About", None, QtGui.QApplication.UnicodeUTF8))

